# Generated by Django 5.1.1 on 2024-09-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
