# Generated by Django 5.1.1 on 2024-09-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dated_added',
            new_name='date_added',
        ),
    ]
